analise_dados_correta = [
    {
    'fornecedores':[
            {
                '6 DO AVESSO COM DE BEB EIRELI':1,
                'BEBIDAS ASTECA LTDA':2,
                'BELLPAR REFRESCOS - EIRELI':3,
                'CACHAÇA DOS AMIGOS':4,
                'CACHAÇA PALMITALZINHO':5,
                'CAFE TERRA DO REI LTDA ME':6,
                'Capri Industria e Comercio de Produtos Alimenticio':7,
                'CARVAO EL SHADDAY':8,
                'CEPAL - CERVEJARIA PAULISTANA LTDA.':9,
                'CHOCOLATES':10,
                'COMERCIAL ZARAGOZA IMP. E EXP. LTDA':11,
                'COMEXIM BEBIDAS':12,
                'CONVENCAO SAO PAULO INDUSTRIA DE BEBIDAS E CONEXOS':13,
                'DANILLA FOODS BRASIL LTDA - PARANA':14,
                'DISTRIBUIDORA':15,
                'E. DEZANI - BEBIDAS':16,
                'E2 DISTRIBUIDORA DE BEBIDAS LTDA':17,
                'ECOBRAZA':18,
                'EDENCOCO COMERCIAL IMPORTADORA E EXPORTADORA LTDA':19,
                'FLORAO ALIMENTOS LTDA':20,
                'FS FOREST SUN INDUSTRIA E COMERCIO DE IMPORTACAO E':21,
                'INDUSTRIA E COMERCIO DE BEBIDAS FORNAZIERO LTDA-EP':22,
                'LEVISSIMA':23,
                'LIOTECNICA TECNOLOGIA EM ALIMENTOS S.A.':24,
                'MAKRO ATACADISTA SA':25,
                'MARCUS PRATES DE LIMA':26,
                'MARQUES BEBIDAS E PARTICIPACOES EIRELI':27,
                'MOCOTOP':28,
                'MONTREAL ENGARRAFADORA DE BEBIDAS LTDA':29,
                'NEWAGE INDUSTRIA DE BEBIDAS LTDA':30,
                'PORTAO DE CAMBUI DOCES E LATICINIOS LTDA':31,
                'PURO SUMO LTDA':32,
                'REFRIX ENVASADORA DE BEBIDAS LTDA':33,
                'SENDAS DISTRIBUIDORA S/A LJ24':34,
                'SENIR EMBALAGENS LTDA':35,
                'SOCORRO INDUSTRIA DE BEBIDAS LTDA.':36,
                'STILUS IND. E COMERCIO DE BEBIDAS LTDA':37,
                'VINHOS BELTRAME INDUSTRIA E COMERCIO LTDA':38,
                'WEW COMERCIO DE PRODUTOS ALIMENTICIOS LTDA':39
            }
        ],
    'tipos':[],
    }
]